FROM php:7.1-fpm
ARG TIMEZONE="Europe/Warsaw"

RUN apt-get update && apt-get install -y \
    openssl git unzip \
    libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng12-dev \
    zlib1g-dev libicu-dev libpq-dev libzip-dev libcurl4-gnutls-dev



# Type docker-php-ext-install to see available extensions
RUN docker-php-ext-install -j$(nproc) iconv mcrypt exif mbstring curl bcmath opcache \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-configure intl && docker-php-ext-install -j$(nproc) intl \
    && docker-php-ext-install -j$(nproc) pdo && docker-php-ext-configure pdo_pgsql \
    && docker-php-ext-install -j$(nproc) pdo_mysql pdo_pgsql mysqli \
    && pecl install zip && docker-php-ext-enable zip


RUN apt-get update && apt-get install -y libmagickwand-6.q16-dev --no-install-recommends \
    && ln -s /usr/lib/x86_64-linux-gnu/ImageMagick-6.8.9/bin-Q16/MagickWand-config /usr/bin \
    && pecl install imagick \
    && echo "extension=imagick.so" > /usr/local/etc/php/conf.d/ext-imagick.ini \
    && rm -rf /var/lib/apt/lists/*


# install xdebug
#RUN pecl install xdebug
#RUN docker-php-ext-enable xdebug
#RUN echo "error_reporting = E_ALL" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#RUN echo "display_startup_errors = On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#RUN echo "display_errors = On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#RUN echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#RUN echo "xdebug.remote_connect_back=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#RUN echo "xdebug.idekey=\"PHPSTORM\"" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
#RUN echo "xdebug.remote_port=9001" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer --version

# Set timezone
RUN ln -snf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime && echo ${TIMEZONE} > /etc/timezone
RUN printf '[PHP]\ndate.timezone = "%s"\n', ${TIMEZONE} > /usr/local/etc/php/conf.d/tzone.ini

WORKDIR "/srv/app"
#RUN usermod -u 1000 www-data

CMD ["php-fpm"]



